-- https://school.programmers.co.kr/learn/courses/30/lessons/157339
SELECT c.CAR_ID, c.CAR_TYPE, ROUND(c.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
ON c.CAR_TYPE = p.CAR_TYPE AND p.DURATION_TYPE = "30일 이상"
AND c.CAR_ID NOT IN (
	SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30'
)
HAVING FEE < 2000000 AND FEE >= 500000
ORDER BY FEE DESC, c.CAR_TYPE ASC, c.CAR_ID DESC